// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/install": {
    params: {};
  };
  "/backends/db": {
    params: {};
  };
  "/backends/package": {
    params: {};
  };
  "/backends/server": {
    params: {};
  };
  "/backends/positionController": {
    params: {};
  };
  "/backends/teacherController": {
    params: {};
  };
  "/backends/errorHandler": {
    params: {};
  };
  "/backends/svg": {
    params: {};
  };
  "/backends/index": {
    params: {};
  };
  "/backends/positionRoutes": {
    params: {};
  };
  "/backends/teacherRoutes": {
    params: {};
  };
  "/fontends/Nav": {
    params: {};
  };
  "/fontends/home": {
    params: {};
  };
  "/fontends/position": {
    params: {};
  };
  "/fontends/teacher": {
    params: {};
  };
  "/fontends/CustomSelect": {
    params: {};
  };
  "/fontends/routes": {
    params: {};
  };
  "/database/create-database": {
    params: {};
  };
  "/database/create-table": {
    params: {};
  };
  "/database/insert-into": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/install" | "/backends/db" | "/backends/package" | "/backends/server" | "/backends/positionController" | "/backends/teacherController" | "/backends/errorHandler" | "/backends/svg" | "/backends/index" | "/backends/positionRoutes" | "/backends/teacherRoutes" | "/fontends/Nav" | "/fontends/home" | "/fontends/position" | "/fontends/teacher" | "/fontends/CustomSelect" | "/fontends/routes" | "/database/create-database" | "/database/create-table" | "/database/insert-into";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/install.tsx": {
    id: "routes/install";
    page: "/install";
  };
  "routes/backend/s-db.tsx": {
    id: "routes/backend/s-db";
    page: "/backends/db";
  };
  "routes/backend/s-package.tsx": {
    id: "routes/backend/s-package";
    page: "/backends/package";
  };
  "routes/backend/s-server.tsx": {
    id: "routes/backend/s-server";
    page: "/backends/server";
  };
  "routes/backend/s-positionController.tsx": {
    id: "routes/backend/s-positionController";
    page: "/backends/positionController";
  };
  "routes/backend/s-teacherController.tsx": {
    id: "routes/backend/s-teacherController";
    page: "/backends/teacherController";
  };
  "routes/backend/s-errorHandler.tsx": {
    id: "routes/backend/s-errorHandler";
    page: "/backends/errorHandler";
  };
  "routes/backend/s-default-svg.tsx": {
    id: "routes/backend/s-default-svg";
    page: "/backends/svg";
  };
  "routes/backend/s-index.tsx": {
    id: "routes/backend/s-index";
    page: "/backends/index";
  };
  "routes/backend/s-positionRoutes.tsx": {
    id: "routes/backend/s-positionRoutes";
    page: "/backends/positionRoutes";
  };
  "routes/backend/s-teacherRoutes.tsx": {
    id: "routes/backend/s-teacherRoutes";
    page: "/backends/teacherRoutes";
  };
  "routes/fontend/s-nav.tsx": {
    id: "routes/fontend/s-nav";
    page: "/fontends/Nav";
  };
  "routes/fontend/s-home.tsx": {
    id: "routes/fontend/s-home";
    page: "/fontends/home";
  };
  "routes/fontend/s-position.tsx": {
    id: "routes/fontend/s-position";
    page: "/fontends/position";
  };
  "routes/fontend/s-teacher.tsx": {
    id: "routes/fontend/s-teacher";
    page: "/fontends/teacher";
  };
  "routes/fontend/s-customSelect.tsx": {
    id: "routes/fontend/s-customSelect";
    page: "/fontends/CustomSelect";
  };
  "routes/fontend/s-routes.tsx": {
    id: "routes/fontend/s-routes";
    page: "/fontends/routes";
  };
  "routes/database/s-create-database.tsx": {
    id: "routes/database/s-create-database";
    page: "/database/create-database";
  };
  "routes/database/s-create-table.tsx": {
    id: "routes/database/s-create-table";
    page: "/database/create-table";
  };
  "routes/database/s-insert-into.tsx": {
    id: "routes/database/s-insert-into";
    page: "/database/insert-into";
  };
};